version: '3.8'

services:
  nginx:
      image: nginx:latest
      container_name: nginx
      ports:
        - "80:80"
      depends_on:
        - web
      volumes:
        - ./dockerfiles/deploy/ngnix/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      environment:
        - NGINX_HOST=localhost
        - NGINX_PORT=80
  web:
    build:
      context: .
      dockerfile: ./dockerfiles/local/Dockerfile
    container_name: fast_neo
    ports:
      - "8000:8000"
    depends_on:
      - neo4j
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
    volumes:
      - .:/app

  neo4j:
    image: neo4j:latest
    container_name: neo4j_db
    environment:
      - NEO4J_AUTH=neo4j/${NEO_PASSWORD}  # Define o usuário e senha do Neo4j
    ports:
      - "7474:7474"  # Porta HTTP para acesso ao Browser do Neo4j
      - "7687:7687"  # Porta Bolt (usada por aplicações como FastAPI)
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs

  
volumes:
  postgres_data:
  neo4j_data:
  neo4j_logs:
